name: First workflow
on: [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo a stroing
              run: echo "Hello World"
            - name: MultiLines command
              run: 
                node -v
                npm -v
    parallel-job-macos:
      runs-on: macos-latest
      steps:
        - name: view SW Version
          run: sw_vers
    dependent-job:
      runs-on: windows-latest
      needs: run-shell-commands
      steps: 
        - name: echo a string
          run: Write-Output "windows String"
        - name: Error Step
          run: dosenotexists                 
                   
