name: Working Dirs & Shell
on: [push]
defaults:
    run:
        shell: bash
jobs:
    display-wd-ubuntu-info:
        runs-on: ubuntu-latest
        steps:
            - name: Display Working Directory and List Files
              run: |
                pwd
                ls -a
                ls -al
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
            - name: Change the Working Directory
              working-directory: /home/runner
              run: pwd    
    # display-wd-windows-info:
    #     runs-on: windows-latest
    #     steps:
    #         - name: Display Working Directory and List Files
    #           run: |
    #             Get-location
    #             dir
    #             echo $env:GITHUB_SHA
    #             echo $env:GITHUB_REPOSITORY
    #             echo $env:GITHUB_WORKSPACE
    display-wd-windows-info:
        runs-on: windows-latest
        steps:
            - name: Display Working Directory and List Files
              run: |
                pwd
                ls -a
                ls -al
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE