name: Working Dirs & Shell
on: [push]
jobs:
    display-wd-ubuntu-info:
        runs-on: ubuntu-latest
        steps:
            - name: Display Working Directory and List Files
              run: |
                pwd
                ls -a
                ls -al
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
    display-wd-windows-info:
                    runs-on: windows-latest
                    steps:
                        - name: Display Working Directory and List Files
                          run: |
                            pwd
                            ls -a
                            ls -al
                            echo $GITHUB_SHA
                            echo $GITHUB_REPOSITORY
                            echo $GITHUB_WORKSPACE
            

